version: '3'

services:
 logstash:
    container_name: my_db_logstash
    build:
      context: .
    restart: always
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./pipeline:/usr/share/logstash/pipeline:ro
      - ./data:/data:rw
    ports:
      - "5004:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"